language: perl

before_install:
  - sudo apt-get install gfortran
  - sudo apt-get install fp-compiler-2.4.4
  - sudo apt-get install g++
  - sudo apt-get install gcj-jdk
  - sudo apt-get install libgtop2-7

install:
  - cpanm -n Alien::FFI
  - cpanm -n ExtUtils::CBuilder
  - cpanm -n Config::AutoConf
  - cpanm -n FFI::CheckLib
  - cpanm -n Math::Int64
  - cpanm -n File::chdir
  - cpanm -n Convert::Binary::C
  - cpanm -n Time::Seconds
  - cpanm -n Devel::PPPort
  - cpanm -n Carp::Always

perl:
  - "5.20"

script:
  - perl Build.PL
  - perl inc/run/travis.pl
  - ./Build --verbose
  - ./Build test --verbose
  - ./Build install --verbose
  
env:
  - FFI_PLATYPUS=1
  - FFI_PLATYPUS_IMPL=RTypes
  - FFI_PLATYPUS_IMPL=Libffi
  - FFI_PLATYPUS_IMPL="Lazy(RTypes)"
  - FFI_PLATYPUS_IMPL="Lazy(Libffi)"
  - FFI_PLATYPUS_IMPL="Debug(RTypes)"
  - FFI_PLATYPUS_IMPL="Debug(Libffi)"
